### ISSUE TITLE
Docker image uses very old version of youtube-dl binary

### ISSUE THREAD

**Issue by dasburninator** [Enriquito/youtube-dl-front#8]
Looks like this is being pulled directly from the alpine repo via APT.
`ENV APK_ADD="git bash youtube-dl ffmpeg"

`bash-5.0# youtube-dl --version
2019.11.28`

This should probably have a script on container startup to pull the latest binary directly from youtube-dl instead of adding it through ENV APK_ADD in the dockerfile.

**Comment by Enriquito** [comment]
Added a curl request in the "run.sh" script to pull new version every time the docker application starts.
Also changed the Dockerfile that it always pull the latest version from the youtube-dl website.

**Comment by dasburninator** [comment]
That works perfect!
